FROM openjdk:24-jdk-slim

ENV APP_PATH=/usr/src/app
RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH

COPY target/windCatchers-0.0.1-SNAPSHOT.jar $APP_PATH/windCatchers.jar

ENTRYPOINT java -Dspring.profiles.active=dev -jar  ${APP_PATH}/windCatchers.jar
